package:
  name: roq-sbe-multicast-test
  version: 1.0

source:
  git_url: ..

build:
  skip: true  # [not unix]

requirements:
  build:
    - {{ compiler('cxx') }}
    - clangdev
    - cmake
    - make
    - pkg-config
  host:
    - abseil-cpp
    - catch2  # [linux]
    - roq-client
    - roq-flags
    - roq-io
    - roq-oss-benchmark
    - roq-oss-catch2  # [osx]

about:
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Roq SBE/multicast Test
